language: 
 - python
python:
 - 3.5.0
install: 
 - pip install -r web/requirements.txt
 - pip install coveralls
script:
 - mkdir web/tests/temp/
 - python3 web/manage.py coverage
after_success:
 - coveralls